name: webserver data

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: pwd check 
      run: |
        echo $(pwd)
    - name: checkout
      uses: actions/checkout@v2
    - name: move static files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "/home/runner/work/notasdeausencia/notasdeausencia/webserver/static"
        remote: "/root/webserver/static"

    - name: move escena1 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "/home/runner/work/notasdeausencia/notasdeausencia/webserver/escena1"
        remote: "/root/webserver/escena1/"

    - name: move escena2 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "/home/runner/work/notasdeausencia/notasdeausencia/webserver/escena2"
        remote: "/root/webserver/escena2/"

    - name: move escena3 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "/home/runner/work/notasdeausencia/notasdeausencia/webserver/escena3"
        remote: "/root/webserver/escena3/"

