name: webserver data

on:
  push:
    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: move textos to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}       
        local: "textos/*"
        remote: "/root/textos/"

    - name: move static files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "webserver/static/*"
        remote: "/root/webserver/static"

    - name: move escena1 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "webserver/escena1/*"
        remote: "/root/webserver/escena1/"

    - name: move escena2 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "webserver/escena2/*"
        remote: "/root/webserver/escena2/"

    - name: move escena3 html files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}        
        local: "webserver/escena3/*"
        remote: "/root/webserver/escena3/"

